---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
  name: {{ .Values.cluster.name }}-crs-0
  namespace: {{ $.Release.Namespace }}
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
  resources:
  - kind: Secret
    name: vsphere-config-secret
  - kind: Secret
    name: cloud-provider-vsphere-credentials
{{- if .Values.vsphereCluster.csi.enabled }}
  - kind: ConfigMap
    name: csi-manifests
{{- end }}
{{- if .Values.vsphereCluster.cpi.enabled }}
  - kind: ConfigMap
    name: cpi-manifests
  - kind: ConfigMap
    name: cpi-manifests-cloud-config
{{- end }}
{{- range $md := .Values.extraResourcesConfigmaps }}
  - kind: ConfigMap
    name: {{ $md.name }}
{{- end }}
{{- range $s := .Values.extraResourcesSecrets }}
  - kind: Secret
    name: {{ $s.name }}
{{- end }}
{{- if .Values.cni.enabled }}
  - kind: ConfigMap
    name: cni-installation
{{- end }}
{{- if .Values.argo.enabled }}
  - kind: ConfigMap
    name: add-cluster-to-argo
  - kind: Secret
    name: add-cluster-to-argo
{{- end }}
