{{- if .Values.machineDeployments }}
{{- range $md := .Values.machineDeployments }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ $.Values.cluster.name }}-{{ $md.name}}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: /var/run/containerd/containerd.sock
          kubeletExtraArgs:
            cloud-provider: external
          {{- if $md.node-labels }}
            node-labels: {{ $md.node-labels}}
          {{- end }}
          name: '{{`{{ local_hostname }}`}}'
        {{- if and $md.taints (gt (len $md.taints) 0) }}
          taints:
          {{- toYaml $md.taints | nindent 10 }}
        {{- end }}
{{- with $.Values.kubeadmConfigSpec.files }}
      files:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- if $.Values.kubeadmConfigSpec.multipath.enabled }}
  {{- if lt (len $.Values.kubeadmConfigSpec.files) 1 }}
      files:
  {{- end }}
      - content: |
          defaults {
            user_friendly_names no
            {{- if $.Values.kubeadmConfigSpec.multipath.find_multipaths }}
            find_multipaths yes
            {{- else }}
            find_multipaths no
            {{- end }}
          }
          devices {
            device {
              vendor                      "NVME"
              product                     "Pure Storage FlashArray"
              path_selector               "queue-length 0"
              path_grouping_policy        group_by_prio
              prio                        ana
              failback                    immediate
              fast_io_fail_tmo            10
              user_friendly_names         no
              no_path_retry               0
              features                    0
              dev_loss_tmo                60
            }
            device {
              vendor                   "PURE"
              product                  "FlashArray"
              path_selector            "service-time 0"
              hardware_handler         "1 alua"
              path_grouping_policy     group_by_prio
              prio                     alua
              failback                 immediate
              path_checker             tur
              fast_io_fail_tmo         10
              user_friendly_names      no
              no_path_retry            0
              features                 0
              dev_loss_tmo             600
            }
          }
          blacklist {
            devnode "^pxd[0-9]*"
            devnode "^pxd*"
            device {
              vendor "VMware"
              product "Virtual disk"
            }
          }
        owner: root:root
        path: /etc/multipath.conf
        permissions: "0644"
{{- end }}
      preKubeadmCommands:
      {{- toYaml $.Values.kubeadmConfigSpec.preKubeadmCommands | nindent 6 }}
      {{- if $.Values.kubeadmConfigSpec.multipath.enabled }}
      - {{ $.Values.kubeadmConfigSpec.multipath.reload_multipath_command }}
      {{- end }}
      users:
      - name: capv
        sshAuthorizedKeys:
        {{- toYaml $.Values.kubeadmConfigSpec.sshAuthorizedKeys | nindent 8 }}
        sudo: ALL=(ALL) NOPASSWD:ALL
{{- end }}
{{- end }}
