{{- if .Values.machineDeployments }}
{{- range $md := .Values.machineDeployments }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ $.Values.cluster.name }}
  name: {{ $.Values.cluster.name }}-{{ $md.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ $.Values.cluster.name }}
  replicas: {{ $md.replicas }}
  selector:
    matchLabels: {}
{{- with $md.strategy }}
  strategy: 
  {{- toYaml . | nindent 4 }}
{{- end }}  
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ $.Values.cluster.name }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $.Values.cluster.name }}-{{ $md.name }}
      clusterName: {{ $.Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: {{ $md.template }}
      version: {{ $md.version }}
{{- end }}
{{- end }}
