{{- if .Values.argo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: add-cluster-to-argo
  namespace: {{ .Release.Namespace }}
stringData:
  data: |-
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: argo-auth-token
      namespace: argo
    type: Opaque
    data:
      token: {{ .Values.argo.auth.token | b64enc }}
type: addons.cluster.x-k8s.io/resource-set
{{- end }}