{{- $defaultSpec := .Values.vsphereMachineTemplate.defaults.spec }}
{{- if .Values.vsphereMachineTemplate.templates }}
{{- range $t := .Values.vsphereMachineTemplate.templates }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: {{ $t.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      cloneMode: {{ $t.spec.cloneMode | default $defaultSpec.cloneMode }}
      datacenter: {{ $t.spec.datacenter | default $.Values.vsphereCluster.datacenter }}
      datastore: {{ $t.spec.datastore | default $defaultSpec.datastore }}
      diskGiB: {{ $t.spec.diskGiB | default $defaultSpec.diskGiB }}
    {{- if $t.spec.additionalDisksGiB }}
      additionalDisksGiB: {{ $t.spec.additionalDisksGiB }}
    {{- end }}
      folder: {{ $t.spec.folder | default $defaultSpec.folder }}
    {{- if $t.spec.specialMemoryMiB }}
      memoryMiB: 10240
    {{- else }}
      memoryMiB: {{ $t.spec.specialMemoryMiB | default $defaultSpec.memoryMiB }}
    {{- end }}
      network:
        {{- toYaml ($t.spec.network | default $defaultSpec.network) | nindent 8 }}
      numCPUs: {{ $t.spec.numCPUs | default $defaultSpec.numCPUs }}
      os: {{ $t.spec.os | default $defaultSpec.os }}
      powerOffMode: {{ $t.spec.powerOffMode | default $defaultSpec.powerOffMode }}
      resourcePool: {{ $t.spec.resourcePool | default $defaultSpec.resourcePool }}
      server: {{ $t.spec.server | default $.Values.vsphereCluster.server }}
      storagePolicyName: "{{ $t.spec.storagePolicyName | default $defaultSpec.storagePolicyName }}"
    {{- if and $t.spec.tagIDs (gt (len $t.spec.tagIDs) 0)  }}
      tagIDs:
      {{- toYaml ($t.spec.tagIDs | default $defaultSpec.tagIDs) | nindent 6 }}
    {{- end }}
    {{- if and $t.spec.pciDevices (gt (len $t.spec.pciDevices) 0)  }}
      pciDevices:
      {{- toYaml ($t.spec.pciDevices | default $defaultSpec.pciDevices) | nindent 6 }}
    {{- end }}
    {{- if $t.spec.customVMXKeys }}
      customVMXKeys:
      {{- toYaml ($t.spec.customVMXKeys | default $defaultSpec.customVMXKeys) | nindent 8 }}
    {{- end }}
      template: {{ $t.spec.template | default $defaultSpec.template }}
      thumbprint: "{{ $t.spec.thumbprint | default $.Values.vsphereCluster.thumbprint }}"
{{- end }}
{{- end }}
